networks:
  atdd-net:
    name: atdd-net
    external: true

services:
  kiosk:
    build:
      context: ../repos/atdd-camping-kiosk
      dockerfile: ../../infra/dockerfiles/Dockerfile-kiosk
    ports:
      - "18081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:mysql://atdd-db:3306/atdd?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=secret
    networks:
      - atdd-net

  admin:
    build:
      context: ../repos/atdd-camping-admin
      dockerfile: ../../infra/dockerfiles/Dockerfile-admin
    ports:
      - "18082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:mysql://atdd-db:3306/atdd?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=secret
    networks:
      - atdd-net

  reservation:
    build:
      context: ../repos/atdd-camping-reservation
      dockerfile: ../../infra/dockerfiles/Dockerfile-reservation
    ports:
      - "18083:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:mysql://atdd-db:3306/atdd?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=secret
    networks:
      - atdd-net
