services:
  kiosk:
    build:
      context: ../repos/atdd-camping-kiosk
      dockerfile: ../../infra/dockerfiles/Dockerfile-kiosk
    ports:
      - "18081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - SERVER_PORT=8080
